---
# jpipes:

    ### Toggle application debugging
    # debug: false

    ### Where plugins are loaded from
    # plugin_dir: /var/lib/jpipes/plugins/

    ### Where plugin configurations live
    # plugin_config_dir: /etc/jpipes/plugins.d/

# log:

    ### Where the log file lives (no log file by default)
    # file: null

    ### The level for which to log.  One of: info, warn, error, fatal, debug
    # level: info

    ### Whether or not to log to console
    # to_console: true

    ### Whether or not to rotate the log file when it reaches `max_bytes`
    # rotate: false

    ### Max size in bytes that a log file can grow until it is rotated.
    # max_bytes: 512000

    ### The maximun number of log files to maintain when rotating
    # max_files: 4


# jenkins:

    ### jenkins api base url
    # url: https://jenkins.example.com

    ### api username
    # username: null

    ### api password
    # password: null


# pipelines:
#     test:
#         job: pipeline-variable-engine-test
#         params:
#             - foo
